#!/bin/sh
# glinet-vlan-qos-setup.sh - Interactive setup wizard for GL.iNet bandwidth QoS
# GPLv3 - see LICENSE

set -euo pipefail

MAIN_SCRIPT="/usr/local/sbin/glinet-vlan-qos.sh"
CONF_FILE="/etc/gl-qos-vlan.conf"

log_info() { echo "INFO: $*"; }
log_warn() { echo "WARN: $*"; }
log_err() { echo "ERR: $*"; }

# ---------- Step 0: Mode selection ----------
select_mode() {
  echo ""
  echo "=== Step 0: Traffic Shaping Mode ==="
  echo "1) QoS (HTB + CAKE) - Per-VLAN/SSID priority with WAN-rooted bandwidth limits"
  echo "2) SQM (CAKE diffserv) - Smart Queue Management on WAN only"
  read -p "Select mode [1-2]: " -r mode
  case "$mode" in
    2) echo "QOS_MODE=sqm" ;;
    1|*) echo "QOS_MODE=qos" ;;
  esac
}

# ---------- Step 1: Model selection ----------
select_model() {
  echo ""
  echo "=== Step 1: Router Model ==="
  echo "1) GL.iNet Flint 2 (GL-MT6000) - OpenWrt 21.02, tc-tiny"
  echo "2) GL.iNet Flint 3 (GL-BE9300) - OpenWrt 23.05, tc-full"
  echo "3) GL.iNet Flint 4 (GL-BE14000) - OpenWrt 21.02, tc-tiny"
  echo "4) GL.iNet Slate 7 (GL-BE3600) - OpenWrt 23.05, tc-full"
  echo "5) GL.iNet Slate 7 Pro (GL-BE10000) - OpenWrt 21.02, tc-tiny"
  echo "6) GL.iNet Beryl 7 (GL-MT3600BE) - OpenWrt 21.02, tc-tiny"
  echo "7) GL.iNet Flint 3e (GL-BE6500) - OpenWrt 23.05, tc-full"
  echo "8) Auto-detect"
  read -p "Select model [1-8]: " -r model
  case "$model" in
    1) echo "QOS_MODEL=flint2" ;;
    2) echo "QOS_MODEL=flint3" ;;
    3) echo "QOS_MODEL=flint4" ;;
    4) echo "QOS_MODEL=slate7" ;;
    5) echo "QOS_MODEL=slate7pro" ;;
    6) echo "QOS_MODEL=beryl7" ;;
    7) echo "QOS_MODEL=flint3e" ;;
    8|*) echo "QOS_MODEL=auto" ;;
  esac
}

# Detect actual model
detect_model_actual() {
  local board
  board=$(cat /etc/board.json 2>/dev/null || echo '{}')
  case "$board" in
    *'"glinet,gl-be14000"'*|*'"glinet,gl-mt6000"'*) echo "flint2" ;;
    *'"qcom,ipq5332-ap-mi01.6"'*) echo "flint3" ;;
    *'"glinet,gl-be3600"'*) echo "flint3" ;;
    *'"glinet,gl-be10000"'*) echo "flint2" ;;
    *'"glinet,gl-mt3600be"'*) echo "flint2" ;;
    *'"qcom,ipq5332-ap-mi04.1-v1"'*) echo "flint3" ;;
    *) echo "unknown" ;;
  esac
}

# ---------- Step 2: Persistence ----------
select_persistence() {
  echo ""
  echo "=== Step 2: Persistence ==="
  echo "1) Enable (apply on boot via rc.local + sysupgrade protection)"
  echo "2) Disable"
  read -p "Select [1-2]: " -r persist
  case "$persist" in
    1) echo "PERSISTENT=1" ;;
    2|*) echo "PERSISTENT=0" ;;
  esac
}

# ---------- Step 3: VLAN/Bridge Priority ----------
select_priority() {
  echo ""
  echo "=== Step 3: Bridge Priority ==="
  echo "Enter priority 1 (highest) through 3 (lowest) for each bridge"
  echo "Available: br-lan, br-iot, br-guest, tailscale0"
  
  local bridges=$(ls -d /sys/class/net/br-* /sys/class/net/tailscale0 2>/dev/null | xargs basename -a 2>/dev/null || echo "br-lan br-iot br-guest tailscale0")
  echo "Detected: $bridges"
  for b in $bridges; do
    read -p "Priority for $b (1=highest, 0=skip): " -r pri
    [ "$pri" -lt 1 ] || [ "$pri" -gt 3 ] && { echo "Invalid priority $pri for $b"; pri=3; }
    echo "PRIOR_$b=$pri"
  done
}

# ---------- Step 4: WAN Bandwidth ----------
select_bandwidth() {
  echo ""
  echo "=== Step 4: WAN Bandwidth Limits ==="
  read -p "WAN upload limit (kbps, e.g., 100000 for 100 Mbps): " -r wan_up
  read -p "WAN download limit (kbps, e.g. 500000 for 500 Mbps): " -r wan_down
  : "${wan_up:=100000}"
  : "${wan_down:=500000}"
  echo "WAN_BW_UP=$wan_up"
  echo "WAN_BW_DOWN=$wan_down"
}

# ---------- Write config ----------
write_config() {
  local mode="$1" model="$2" persist="$3" wan_up="$4" wan_down="$5"
  cat > "$CONF_FILE" <<EOF
# Generated by glinet-vlan-qos-setup.sh
QOS_MODE=$mode
QOS_MODEL=$model
PERSISTENT=$persist
WAN_BW_UP=$wan_up
WAN_BW_DOWN=$wan_down
QOS_LAN_BW_UP=200000
QOS_LAN_BW_DOWN=500000
QOS_IOT_BW_UP=100000
QOS_IOT_BW_DOWN=200000
QOS_GUEST_BW_UP=100000
QOS_GUEST_BW_DOWN=200000
QOS_TAILSCALE_BW_UP=200000
QOS_TAILSCALE_BW_DOWN=500000
CAKE_ENABLE=1
EOF
  echo "Wrote $CONF_FILE"
}

# ---------- Setup persistence ----------
setup_persistence() {
  local persist="$1"
  [ "$persist" != "1" ] && return 0
  log_info "Setting up persistence..."
  
  # Add to rc.local
  if [ -f /etc/rc.local ]; then
    grep -q "glinet-vlan-qos.sh start" /etc/rc.local 2>/dev/null || {
      sed -i '/^exit 0$/d' /etc/rc.local 2>/dev/null || true
      printf '\n# VLAN QoS persistence\nif [ -x /usr/local/sbin/glinet-vlan-qos.sh ]; then\n  /usr/local/sbin/glinet-vlan-qos.sh start >/dev/null 2>&1 || true\nfi\n' >> /etc/rc.local
      log_info "Added to rc.local"
    }
  fi
  
  # Add to sysupgrade protection
  mkdir -p /etc/sysupgrade.conf.d
  printf '/usr/local/sbin/glinet-vlan-qos.sh\n/etc/gl-qos-vlan.conf\n' > /etc/sysupgrade.conf.d/glinet-qos.conf
  log_info "Added to sysupgrade protection"
}

# ---------- Main ----------
main() {
  echo "GL.iNet Bandwidth QoS Setup Wizard"
  echo "===================================="
  
  local mode model persist wan_up wan_down priorities
  
  mode=$(select_mode)
  model=$(select_model)
  persist=$(select_persistence)
  bandwidth_vals=$(select_bandwidth)
  wan_up=$(echo "$bandwidth_vals" | grep "WAN_BW_UP=" | cut -d= -f2)
  wan_down=$(echo "$bandwidth_vals" | grep "WAN_BW_DOWN=" | cut -d= -f2)
  priorities=$(select_priority)
  
  echo ""
  echo "=== Summary ==="
  echo "Mode: $mode"
  echo "Model: $model"
  echo "Persistent: $persist"
  echo "WAN: ${wan_up} up / ${wan_down} down kbps"
  
  read -p "Write config and apply? [y/N]: " -r confirm
  case "$confirm" in
    y|Y|yes)
      write_config "$mode" "$model" "$persist" "$wan_up" "$wan_down" > /dev/null
      setup_persistence "$persist"
      echo "Run '$MAIN_SCRIPT start' to apply"
      ;;
    *)
      log_info "Cancelled"
      exit 0
      ;;
  esac
}

main "$@"